server:
  port: 8182

spring:
  application:
    name: message-app

  datasource:
    url: jdbc:mysql://localhost:3306/messagingapplication
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
